### ISSUE TITLE
Console as FormType

### ISSUE THREAD

**Issue by helios-ag** [CoreSphere/ConsoleBundle#67]
Any plans for  this?

**Comment by laszlokorte** [comment]
Thank you for your suggestion, currently I do not have plans to implement this. 

Could you elaborate on how this would work and how you would like to use it please?

**Comment by helios-ag** [comment]
Well, we have symfony based app, that have a some console commands that executed via cron or manually. I think it would be nice to have console at backend, that can be easily integrated into current app via forms, so users will be able to execute commands without using ssh.

**Comment by laszlokorte** [comment]
I am not sure how one would build this because the console is not just a form field but kind of a whole form of itself. It has a url it needs to submitted to via ajax in order to get the interactive behavior. So it is not a form field that can easily mixed with other form fields.

Currently I have no time to investigate this further but if you have concrete ideas how to implement it I like to hear about them. If there is a sensible way to implement this I will accept a pull request as well.

**Comment by helios-ag** [comment]
On second thought, probably formtype isn't best approach, but embedding console onto page with simple solution would be nice, maybe custom twig function, with ability to pass some preconfigured options? 
something like this:
```jinja
{{ core_console('default_instance') }}
```
and config.yml
```yaml
coresphere_console:
    default_instance:
        filtering:
           blacklist: [ 'doctrine:*', 'generate:*', 'config:dump-reference' ]
        #other options   
```
